# Generated by Django 2.2.16 on 2020-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201117_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
