# Generated by Django 2.2.16 on 2020-11-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201119_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='image',
            new_name='imagen',
        ),
    ]
