# Generated by Django 2.2.16 on 2020-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
